"""The common module that is used in most other modules"""

from amphimixis.core.general import constants, tools
from amphimixis.core.general.general import (
    IUI,
    Arch,
    Build,
    BuildSystem,
    CompilerFlags,
    CompilerFlagsAttrs,
    DummyBuildSystem,
    DummyRunner,
    IHighLevelBuildSystem,
    ILowLevelBuildSystem,
    MachineAuthenticationInfo,
    MachineInfo,
    NullUI,
    ProfileStats,
    Project,
    ProjectStats,
    Toolchain,
    ToolchainAttrs,
    BuildSystemIsNotHighLevel,
    BuildSystemIsNotLowLevel,
)


__all__ = [
    "Project",
    "Build",
    "MachineInfo",
    "Arch",
    "BuildSystem",
    "IHighLevelBuildSystem",
    "ILowLevelBuildSystem",
    "MachineAuthenticationInfo",
    "constants",
    "tools",
    "MachineInfo",
    "MachineAuthenticationInfo",
    "IUI",
    "NullUI",
    "Toolchain",
    "ToolchainAttrs",
    "CompilerFlagsAttrs",
    "CompilerFlags",
    "ProfileStats",
    "ProjectStats",
    "DummyBuildSystem",
    "DummyRunner",
    "BuildSystemIsNotHighLevel",
    "BuildSystemIsNotLowLevel",
]
