"""The common module that is used in most other modules"""

from amphimixis.core.general import constants, tools
from amphimixis.core.general.general import (
    DUMMY_RUNNER,
    IUI,
    NULL_UI,
    Arch,
    Build,
    BuildSystem,
    CompilerFlags,
    CompilerFlagsAttrs,
    IHighLevelBuildSystem,
    ILowLevelBuildSystem,
    MachineAuthenticationInfo,
    MachineInfo,
    ProfileStats,
    Project,
    ProjectStats,
    Toolchain,
    ToolchainAttrs,
)

__all__ = [
    "Project",
    "Build",
    "MachineInfo",
    "Arch",
    "BuildSystem",
    "IHighLevelBuildSystem",
    "ILowLevelBuildSystem",
    "MachineAuthenticationInfo",
    "constants",
    "tools",
    "MachineInfo",
    "MachineAuthenticationInfo",
    "IUI",
    "NULL_UI",
    "Toolchain",
    "ToolchainAttrs",
    "CompilerFlagsAttrs",
    "CompilerFlags",
    "ProfileStats",
    "ProjectStats",
    "DUMMY_RUNNER",
]
