FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y python3 python3-pip sshpass rsync time linux-tools-generic && \
    pip install --break-system-packages PyYAML && \
    rm /usr/bin/perf && \
    ln -s /usr/lib/linux-tools/6.8.0-90-generic/perf /usr/bin/perf

WORKDIR /workspace
CMD ["bash", "-c", "touch secret_ishtar && tail -f /dev/null"]
